### PR TITLE
from same mnemonic, to generate key is the same of the libra cli gene…

### PR DESCRIPTION
**Pull request by wenshenjun**
Update KeyFactory & Pbkdf code, from same mnemonic, to generate key is the same of the libra cli generate.

### CODE REVIEW

**Comment by smiled0g** [comment]
Thank you so much for the PR! Have you tested with browser yet? 

Last time I tried, the browserify's crypto lib didn't suppport sha3-256

**Comment by wenshenjun** [comment]
> Thank you so much for the PR! Have you tested with browser yet?
> 
> Last time I tried, the browserify's crypto lib didn't suppport sha3-256

sorry,I don't test with browser. can use this package https://github.com/emn178/js-sha3?

**Comment by wenshenjun** [comment]
now work with browser. @smiled0g

**Comment by smiled0g** [comment]
Hey @wenshenjun awesome work! Let me check real quick and will merge if it works on the web.

**Comment by smiled0g** [comment]
> now work with browser. @smiled0g

@wenshenjun I can't get it to work in browser. One problem I found is that `writeBigUInt64LE` is not implemented in the https://github.com/feross/buffer (Buffer's shim) package yet. How did you work around this?

**Comment by smiled0g** [comment]
@wenshenjun I have pushed the code that make this works on browser. Thanks so much for your great effort! I'm going to merge this now.

**Comment by wenshenjun** [comment]
sorry, i just test `sha-3` in browser. i can't start `example`. So I can't test the entire project in the browser.

But the following code is wrong.
```javascript
const childDepthBuffer = Buffer.from(
      BigInt(childDepth)
        .toString(16)
        .padStart(16, '0')
        .slice(0, 16),
      'hex',
    ) 
```
You can fix with following code. or util class.
```javascript
 const childDepthBuffer = Buffer.alloc(8)
 const childDepthHex = childDepth.toString(2)
 let low = childDepthHex;
 let height = '0';
 if(childDepthHex.length > 32){
   low = childDepthHex.substring(0, 32)
   height = childDepthHex.substr(32)
 }
 childDepthBuffer.writeUInt32LE(parseInt(low, 2), 0)
 childDepthBuffer.writeUInt32LE(parseInt(height, 2), 4)
```


By the way, What is the version of nodejs you use?

**Pull request merged**
